// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TagIt.DBContext;

namespace TagIt.Migrations
{
    [DbContext(typeof(TagItDBContext))]
    [Migration("20180818232457_table-creation")]
    partial class tablecreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TagIt.DataObject.TagBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MemberId");

                    b.Property<string>("SiteImageUrl");

                    b.Property<string>("SiteTitle");

                    b.Property<string>("TagType");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("TagBlock");
                });
#pragma warning restore 612, 618
        }
    }
}
